export type Property = {
  id: string;
  title: string;
  location: string;
  university: string;
  distanceKm: number;
  price: number;
  roomType: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  available: boolean;
  furnished: boolean;
  amenities: string[];
  image: string;
  imageAlt: string;
  landlord: string;
  landlordAvatar: string;
  landlordAvatarAlt: string;
  responseRate: number;
  availableFrom: string;
  listedDaysAgo: number;
  bedrooms: number;
  bathrooms: number;
  description: string;
};

// Backend integration point: Replace with API call to GET /api/properties?filters=...
export const allProperties: Property[] = [
{
  id: 'prop-001',
  title: 'The Varsity Loft — En-Suite Rooms',
  location: 'Observatory, Cape Town',
  university: 'UCT',
  distanceKm: 0.8,
  price: 4200,
  roomType: 'En-Suite',
  rating: 4.9,
  reviewCount: 47,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'laundry', 'kitchen', 'security'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_18ba03398-1771488812434.png",
  imageAlt: 'Modern en-suite student room with white walls and desk near window',
  landlord: 'Sipho Dlamini',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_14a5ca983-1763300171126.png",
  landlordAvatarAlt: 'Middle-aged man in smart casual attire smiling confidently',
  responseRate: 97,
  availableFrom: '1 May 2026',
  listedDaysAgo: 2,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Modern en-suite rooms with private bathroom, desk, and wardrobe. 5-minute walk to UCT upper campus.'
},
{
  id: 'prop-002',
  title: 'Braamfontein Student House',
  location: 'Braamfontein, Johannesburg',
  university: 'Wits',
  distanceKm: 1.2,
  price: 2800,
  roomType: 'Single Room',
  rating: 4.7,
  reviewCount: 31,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'kitchen', 'security', 'parking'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1068df229-1772203557350.png",
  imageAlt: 'Cozy single student room with wooden floors and natural light',
  landlord: 'Thandi Mokoena',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_10a397da6-1772094815227.png",
  landlordAvatarAlt: 'Young woman with natural hair smiling warmly',
  responseRate: 92,
  availableFrom: '15 Apr 2026',
  listedDaysAgo: 5,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Spacious single room in a well-maintained student house. Shared kitchen and lounge. 15-min walk to Wits.'
},
{
  id: 'prop-003',
  title: 'Hatfield Studio Apartments',
  location: 'Hatfield, Pretoria',
  university: 'UP',
  distanceKm: 0.5,
  price: 5500,
  roomType: 'Studio',
  rating: 4.8,
  reviewCount: 28,
  verified: true,
  available: false,
  furnished: true,
  amenities: ['wifi', 'parking', 'gym', 'security'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_10d6bb2b9-1773665075955.png",
  imageAlt: 'Compact studio apartment with kitchenette and modern furniture',
  landlord: 'Rikus van der Berg',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_15323d9ba-1772556075899.png",
  landlordAvatarAlt: 'Young man in casual shirt with warm smile outdoors',
  responseRate: 88,
  availableFrom: '1 Jul 2026',
  listedDaysAgo: 8,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Self-contained studio with kitchenette, private bathroom, and covered parking. Steps from UP main gate.'
},
{
  id: 'prop-004',
  title: 'Mowbray Shared Residence',
  location: 'Mowbray, Cape Town',
  university: 'UCT',
  distanceKm: 1.5,
  price: 2100,
  roomType: 'Shared Room',
  rating: 4.5,
  reviewCount: 62,
  verified: true,
  available: true,
  furnished: false,
  amenities: ['wifi', 'laundry', 'kitchen'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_12c936ae9-1772145093120.png",
  imageAlt: 'Shared student room with two beds and organized storage space',
  landlord: 'Amara Osei',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_1e5336137-1771896332044.png",
  landlordAvatarAlt: 'Young woman with dark hair smiling in campus setting',
  responseRate: 79,
  availableFrom: '1 May 2026',
  listedDaysAgo: 14,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Budget-friendly shared room in a large student house. Unfurnished — bring your own bed and desk.'
},
{
  id: 'prop-005',
  title: 'Greyville Heights — Furnished Rooms',
  location: 'Greyville, Durban',
  university: 'UKZN',
  distanceKm: 0.9,
  price: 3100,
  roomType: 'En-Suite',
  rating: 4.6,
  reviewCount: 19,
  verified: false,
  available: true,
  furnished: true,
  amenities: ['wifi', 'security', 'kitchen', 'laundry'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b650c633-1772202771336.png",
  imageAlt: 'Furnished en-suite room with study area and private bathroom',
  landlord: 'Priya Naidoo',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_19c0f0964-1772488339944.png",
  landlordAvatarAlt: 'Woman with glasses and professional appearance smiling',
  responseRate: 85,
  availableFrom: '1 May 2026',
  listedDaysAgo: 3,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Well-furnished en-suite rooms in a secure complex. All utilities included in the monthly rate.'
},
{
  id: 'prop-006',
  title: 'Stellenbosch Central Cottage',
  location: 'Central, Stellenbosch',
  university: 'SU',
  distanceKm: 0.3,
  price: 3800,
  roomType: 'Single Room',
  rating: 4.9,
  reviewCount: 54,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'parking', 'garden', 'kitchen'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_10b41dcd4-1772204106362.png",
  imageAlt: 'Charming single room in cottage with warm lighting and wooden desk',
  landlord: 'Liezel Joubert',
  landlordAvatar: "https://images.unsplash.com/photo-1511373800525-05da6d924ef2",
  landlordAvatarAlt: 'Blonde woman smiling in outdoor natural setting',
  responseRate: 99,
  availableFrom: '1 Feb 2026',
  listedDaysAgo: 21,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Charming cottage room in the heart of Stellenbosch. Garden access, fully furnished, 5-min walk to SU.'
},
{
  id: 'prop-007',
  title: 'Sunnyside Bachelor Flat',
  location: 'Sunnyside, Pretoria',
  university: 'UP',
  distanceKm: 2.1,
  price: 3400,
  roomType: 'Studio',
  rating: 4.3,
  reviewCount: 12,
  verified: false,
  available: true,
  furnished: false,
  amenities: ['wifi', 'security', 'parking'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_147c47605-1767117286747.png",
  imageAlt: 'Open-plan bachelor flat with large windows and city view',
  landlord: 'Nkosi Mahlangu',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_124ddf771-1765167525499.png",
  landlordAvatarAlt: 'Man with glasses in professional setting smiling',
  responseRate: 71,
  availableFrom: '15 May 2026',
  listedDaysAgo: 7,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Spacious bachelor flat with open-plan living and kitchen area. Secure parking included.'
},
{
  id: 'prop-008',
  title: 'Rondebosch Rooms — Walking Distance',
  location: 'Rondebosch, Cape Town',
  university: 'UCT',
  distanceKm: 0.6,
  price: 4800,
  roomType: 'En-Suite',
  rating: 4.7,
  reviewCount: 38,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'laundry', 'kitchen', 'security', 'gym'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17af96bbc-1774433516981.png",
  imageAlt: 'Modern en-suite room with queen bed and study nook near window',
  landlord: 'David Hendricks',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_1e25c3770-1772187540586.png",
  landlordAvatarAlt: 'Professional man in business casual attire with confident smile',
  responseRate: 94,
  availableFrom: '1 Apr 2026',
  listedDaysAgo: 1,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Premium en-suite rooms in a purpose-built student complex. Full gym and laundry facilities on-site.'
},
{
  id: 'prop-009',
  title: 'Auckland Park Shared House',
  location: 'Auckland Park, Johannesburg',
  university: 'UJ',
  distanceKm: 1.0,
  price: 2400,
  roomType: 'Shared Room',
  rating: 4.4,
  reviewCount: 25,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'kitchen', 'laundry'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_129f93dce-1772145093374.png",
  imageAlt: 'Neat shared bedroom in a bright student house with twin beds',
  landlord: 'Fatima Essop',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_1459b9ea0-1763295924782.png",
  landlordAvatarAlt: 'Woman with hijab smiling in professional environment',
  responseRate: 90,
  availableFrom: '1 May 2026',
  listedDaysAgo: 4,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Friendly student house near UJ. Shared room with a fellow student. All bills included.'
},
{
  id: 'prop-010',
  title: 'Westdene Garden Cottage',
  location: 'Westdene, Johannesburg',
  university: 'UJ',
  distanceKm: 1.8,
  price: 3600,
  roomType: 'Single Room',
  rating: 4.6,
  reviewCount: 17,
  verified: true,
  available: false,
  furnished: false,
  amenities: ['wifi', 'parking', 'garden', 'kitchen'],
  image: "https://images.unsplash.com/photo-1730908794727-235a188f7f30",
  imageAlt: 'Garden cottage room with leafy outdoor view and natural wood interior',
  landlord: 'Gerhard Botha',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_1d1d3c0e1-1772408040060.png",
  landlordAvatarAlt: 'Older man with grey beard smiling outdoors in casual wear',
  responseRate: 82,
  availableFrom: '1 Jun 2026',
  listedDaysAgo: 11,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Quiet garden cottage with private entrance. Unfurnished but includes fridge and stove.'
},
{
  id: 'prop-011',
  title: 'Umbilo Budget Rooms',
  location: 'Umbilo, Durban',
  university: 'UKZN',
  distanceKm: 2.4,
  price: 1800,
  roomType: 'Shared Room',
  rating: 4.1,
  reviewCount: 33,
  verified: false,
  available: true,
  furnished: false,
  amenities: ['wifi', 'kitchen', 'laundry'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1068df229-1772203557350.png",
  imageAlt: 'Simple budget student room with basic furniture and natural light',
  landlord: 'Zanele Buthelezi',
  landlordAvatar: "https://images.unsplash.com/photo-1620934505162-9f4cacf0e94e",
  landlordAvatarAlt: 'Young woman with braids in casual clothing smiling',
  responseRate: 68,
  availableFrom: '1 May 2026',
  listedDaysAgo: 19,
  bedrooms: 1,
  bathrooms: 1,
  description: 'Most affordable option near UKZN. Basic shared room, suitable for students on a tight budget.'
},
{
  id: 'prop-012',
  title: 'De Waal Drive Luxury Apartment',
  location: 'Gardens, Cape Town',
  university: 'UCT',
  distanceKm: 3.2,
  price: 7800,
  roomType: 'Apartment',
  rating: 4.8,
  reviewCount: 9,
  verified: true,
  available: true,
  furnished: true,
  amenities: ['wifi', 'parking', 'gym', 'security', 'laundry'],
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1a06e8448-1768979391498.png",
  imageAlt: 'Luxury apartment with mountain view, modern kitchen and open-plan living',
  landlord: 'Marco de Villiers',
  landlordAvatar: "https://img.rocket.new/generatedImages/rocket_gen_img_12fc6cbe7-1772369417485.png",
  landlordAvatarAlt: 'Professional man in suit with confident smile in office setting',
  responseRate: 96,
  availableFrom: '1 May 2026',
  listedDaysAgo: 6,
  bedrooms: 2,
  bathrooms: 2,
  description: 'Premium 2-bedroom apartment with Table Mountain views. Fully furnished, undercover parking, concierge.'
}];